# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-dj-ctrl"
BBFILE_PATTERN_meta-dj-ctrl = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-dj-ctrl = "6"

LAYERDEPENDS_meta-dj-ctrl = "core"
LAYERSERIES_COMPAT_meta-dj-ctrl = "scarthgap"
