#!/usr/bin/env bash

cp sources/meta-dj-ctrl/scripts/bblayers.conf.sample build/conf/bblayers.conf
cp sources/meta-dj-ctrl/scripts/local.conf.sample build/conf/local.conf

source sources/openembedded-core/oe-init-build-env build
